baseurl = "/"
title = "Jason I. Carter"
author = "Jason Carter"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Jason I. Carter"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "/about/"
[[menu.main]]
    name = "Services"
    url  = "/services/"
[[menu.main]]
    name = "Contact"
    url  = "/contact"
